In [4]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


# dot() operator for matrix multiplication

In [14]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic = time.time()
c= np.dot(a,b)
toc = time.time()
print(c)
print("Vectorization Time taken:" + str((toc-tic)*1000) + "ms")

c=0;
tic=time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc=time.time()
print(c)
print("Non vectoriztion time:" + str(1000*(toc-tic))+"ms")


249970.233791
Vectorization Time taken:1.0039806365966797ms
249970.233791
Non vectoriztion time:540.7273769378662ms


In [22]:
print(a.shape)
print(b.shape)

(1000000,)
(1000000,)


# Broadcasting example

In [26]:
A = np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [28]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [30]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


# Generate a five random gaussian variables & Understand Vector dimensions

In [40]:
a = np.random.rand(5)

In [41]:
print(a)
print(a.shape)
print(np.dot(a,a.T))

[ 0.50333545  0.26200909  0.14787376  0.06876887  0.88200998]
(5,)
1.12653274105


In [44]:
a= np.random.rand(5,1)
print(a)


[[ 0.41127627]
 [ 0.7170398 ]
 [ 0.77950263]
 [ 0.62153846]
 [ 0.20021156]]


In [45]:
print(a.T)


[[ 0.41127627  0.7170398   0.77950263  0.62153846  0.20021156]]


In [46]:
print(np.dot(a,a.T))

[[ 0.16914817  0.29490146  0.32059093  0.25562402  0.08234226]
 [ 0.29490146  0.51414608  0.55893441  0.44566782  0.14355966]
 [ 0.32059093  0.55893441  0.60762435  0.48449087  0.15606544]
 [ 0.25562402  0.44566782  0.48449087  0.38631006  0.12443919]
 [ 0.08234226  0.14355966  0.15606544  0.12443919  0.04008467]]
